### ISSUE TITLE
What is IDE

### ISSUE THREAD

**Issue by nonsensibl** [PaulSalaun/ms-reward-bot#1]
Title

**Comment by Tatnux** [comment]
Integrated development environment, like Visual Studio Code or PyCharm

**Comment by Morena36** [comment]
I would like there to be more steps to follow because I don't understand anything. I thought I could use CMD to run it, but I have never used an IDE.

**Comment by Morena36** [comment]
PS D:\Downloads\BOTNUEVO2323\ms-reward-bot> run main.py
run : The term 'run' is not recognized as the name of a cmdlet, function, script file, or executable program. Check if you spelled the name correctly
Or, if you included a path, verify that the path is correct and try again.
Online: 1 Character: 1
+ run main.py
+ ~~~
     + CategoryInfo : ObjectNotFound: (run:String) [], CommandNotFoundException
     + FullyQualifiedErrorId : CommandNotFoundException
 
PS D:\Downloads\NEWBOTT2323\ms-reward-bot>

**Comment by danni551** [comment]
python main.py
